### ISSUE TITLE
Codificar HTML pagina registro de Coach

### ISSUE THREAD

**Issue by JulianTic3** [JulianTic3/Ciclo3SeguimientoNutricional#29]

**Comment by NicoBer5** [comment]
@page
@model NutricionApp.FrontEnd.Pages.CoachModel
@{  
}

<br />
<h2 class="text-info">Registro Coach</h2>
<div class="border">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text danger"></div>
            <div class="container" style="padding:20px;">
              <div class="form-group">
                  <div class="row">
                      <div class="col-sm-1">
                          <label for="nombre">Nombre:</label>
                      </div>
                      <div class="col-sm-4">
                          <input type="text" name="nombre" class="form-control" />
                      </div>
                      
                  </div>
              </div>  

              <div class="form-group">
                  <div class="row">
                      <div class="col-sm-1">
                          <label for="nombre">Apellidos:</label>
                      </div>
                      <div class="col-sm-4">
                          <input type="text" name="apellidos" class="form-control" />
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <div class="row">
                      <div class="col-sm-1">
                          <label for="telefono">Telefono:</label>
                      </div>
                      <div class="col-sm-4">
                          <input type="text" name="telefono" class="form-control" />
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <div class="row">
                      <div class="col-sm-1">
                          <label for="correo">Correo:</label>
                      </div>
                      <div class="col-sm-4">
                          <input type="text" name="correo" class="form-control" />
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <div class="row">
                      <div class="col-sm-1">
                          <label for="id">ID:</label>
                      </div>
                      <div class="col-sm-4">
                          <input type="text" name="id" class="form-control" />
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <div class="row">
                      <div class="col-sm-2">
                          <label for="especialidad">Especialidad:</label>
                      </div>
                      <div class="col-sm-3">
                          <input type="text" name="especialidad" class="form-control" />
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <div class="row">
                      <div class="col-sm-2">
                          <label for="certificacion">Certificacion:</label>
                      </div>
                      <div class="col-sm-3">
                          <input type="text" name="certificacion" class="form-control" />
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <div class="row">
                      <div class="col-sm-2">
                          <input type="submit" value="Registrar" class="btn btn-primary form-control">
                      </div> 
                       <div class="col-sm-2">
                          <input type="submit" value="Editar" class="btn btn-primary form-control">
                        </div> 
                        <div class="col-sm-1">
                            <a asp-page="/Index" class="btn btn-success" form-control>Home</a>
                        </div>
                  </div>
              </div>
            </div>
    </form>
</div>
