### ISSUE TITLE
Realizar interface y Repositorio Valoración

### ISSUE THREAD

**Issue by JulianTic3** [JulianTic3/Ciclo3SeguimientoNutricional#32]

**Comment by Jdrew92** [comment]
### IRepositorioValoracion

    using System;
    using System.Collections.Generic;
    using NutricionApp.Dominio;
    namespace NutricionApp.Persistencia
    {
        public interface IRepositorioValoracion{
            IEnumerable<Valoracion> getAllValoraciones();
            Valoracion addValoracion(Valoracion valoracion);
            Valoracion getValoracion(int idValoracion);
            Valoracion updateValoracion(Valoracion valoracion);
            void removeValoracion(int idValoracion);
        }
    }

### RepositorioValoracion

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using NutricionApp.Dominio;
    namespace NutricionApp.Persistencia
    {
        public class RepositorioValoracion : IRepositorioValoracion
        {
            private readonly AppContext _appContext;
    
            public RepositorioValoracion(){
                _appContext = new AppContext();
            }
            public Valoracion addValoracion(Valoracion valoracion)
            {
                var nuevaValoracion = _appContext.Valoraciones.Add(valoracion);
                _appContext.SaveChanges();
                return nuevaValoracion.Entity;
            }
    
            public IEnumerable<Valoracion> getAllValoraciones()
            {
                return _appContext.Valoraciones;
            }
    
            public Valoracion getValoracion(int idValoracion)
            {
                return _appContext.Valoraciones.FirstOrDefault(v=>v.Id == idValoracion);
            }
    
            public void removeValoracion(int idValoracion)
            {
                var valoracionEncontrado = _appContext.Valoraciones.FirstOrDefault(v=>v.Id == idValoracion);
                if(valoracionEncontrado == null)
                    return;
                _appContext.Valoraciones.Remove(valoracionEncontrado);
                _appContext.SaveChanges();
            }
    
            public Valoracion updateValoracion(Valoracion valoracion)
            {
                var valoracionEncontrado = _appContext.Valoraciones.FirstOrDefault(v=>v.Id == valoracion.Id);
                if(valoracionEncontrado != null){
                    valoracionEncontrado.Fecha = valoracion.Fecha;
                    valoracionEncontrado.Peso = valoracion.Peso;
                    valoracionEncontrado.Estatura = valoracion.Estatura;
                    valoracionEncontrado.CaloriasConsumidas = valoracion.CaloriasConsumidas;
                    valoracionEncontrado.Historia = valoracion.Historia;
                    _appContext.SaveChanges();
                }
                return valoracionEncontrado;
            }
        }
    }
