### ISSUE TITLE
Realizar interface y repositorio Historia

### ISSUE THREAD

**Issue by JulianTic3** [JulianTic3/Ciclo3SeguimientoNutricional#33]

**Comment by NicoBer5** [comment]
Irepositorio Historia

using System;
using System.Collections.Generic;
using System.Linq;
using NutricionApp.Dominio;

namespace NutricionApp.Persistencia
{
    public interface IRepositorioHistoria
    {
        IEnumerable<Historia> GetAllHistoria();
        Historia AddHistoria(Historia historia);
        Historia UpdateHistoria(Historia historia);
        void DeleteHistoria(int IdHistoria);
        Historia GetHistoria(int IdHistoria);
    }
}
Repositorio Historia
using System.Collections.Generic;
using NutricionApp.Dominio;
using NutricionApp.Persistencia;
using System.Linq; 
namespace NutricionApp.Persistencia
{
    public class RepositorioPaciente:IRepositorioHistoria
    {
        private readonly NutricionApp.Persistencia.AppContext _appContext;
        public RepositorioHistoria(NutricionApp.Persistencia.AppContext _appContext)
        {
            _appContext = appContext;
        }
        Historia IRepositorioHistoria.AddHistoria(Historia historia)
        {
            var historiaAdd=_appContext.Historia.Add(historia);
            _appContext.SaveChanges();
            return historiaAdd.Entity;
        }
        Historia IRepositorioHistoria.UpdateHistoria(Historia historia)
        {
             var historiaBusqueda=_appContext.Historia.FirstOrDefault(p => p.Id==historia.Id);
            if(historiaBusqueda!=null)
            {
                historiaBusqueda.Fecha=historia.Fecha;
                historiaBusqueda.Diagnostico=historia.Diagnostico;
                historiaBusqueda.Paciente=historia.Paciente;
                _appContext.SaveChanges();
            }   
            return historiaBusqueda;
        }
        void IRepositorioHistoria.DeleteHistoria(int IdHistoria)
        {
            var historiaBusqueda=_appContext.Historia.FirstOrDefault(p => p.Id==IdHistoria);
            if(historiaBusqueda==null)
            return;
            _appContext.Historia.Remove(historiaBusqueda);
            _appContext.SaveChanges();
        }
        Historia IRepositorioHistoria.GetHistoria(int IdHistoria)
        {
            var historiaBusqueda=_appContext.Historia.FirstOrDefault(p => p.Id==IdHistoria);
            return historiaBusqueda;
        }
        IEnumerable<Historia> IRepositorioHistoria.GetAllHistoria()
        {
            return _appContext.Historia;
        }
    }
}
