### ISSUE TITLE
Realizar interface y repositorio Nutricionista

### ISSUE THREAD

**Issue by JulianTic3** [JulianTic3/Ciclo3SeguimientoNutricional#35]

**Comment by Sergioabc94** [comment]
**IRepositorioNutricionista**

using System;
using System.Collections.Generic;
using NutricionApp.Dominio;

namespace NutricionApp.Persistencia
{
    public interface IRepositorioNutricionista
    {
        IEnumerable<Nutricionista> AllNutricionistas();
        Nutricionista AddNutricionista(Nutricionista nutricionista);
        Nutricionista UpdateNutricionista(Nutricionista nutricionista);
        Nutricionista GetNutricionista(int IdNutricionista);
        void DeleteNutricionista(int IdNutricionista);

    }
}



**RepositorioNutricionista**

using System;
using System.Collections.Generic;
using System.Linq;
using NutricionApp.Dominio;

namespace NutricionApp.Persistencia
{
    public class RepositorioNutricionista : IRepositorioNutricionista
    {
        private readonly AppContext _appContext;
        public RepositorioNutricionista(AppContext appContext)
        {
            _appContext = appContext;
        }
        public IEnumerable<Nutricionista> AllNutricionistas()
        {
            return _appContext.Nutricionistas;
        }
        public Nutricionista AddNutricionista(Nutricionista nutricionista)
        {
            var nutricionistaAdicionado = _appContext.Nutricionistas.Add(nutricionista);
            _appContext.SaveChanges();
            return nutricionistaAdicionado.Entity;
        }
        public Nutricionista UpdateNutricionista(Nutricionista Nutricionista)
        {
            var nutricionistaEncontrado = _appContext.Nutricionistas.FirstOrDefault(n => n.Id == Nutricionista.Id);
            if (nutricionistaEncontrado != null)
            {
                nutricionistaEncontrado.Id = Nutricionista.Id;
                nutricionistaEncontrado.Nombre = Nutricionista.Nombre;
                nutricionistaEncontrado.Apellidos = Nutricionista.Apellidos;
                nutricionistaEncontrado.Identificacion = Nutricionista.Identificacion;
                nutricionistaEncontrado.Correo = Nutricionista.Correo;
                nutricionistaEncontrado.Contrasena = Nutricionista.Contrasena;
                nutricionistaEncontrado.Telefono = Nutricionista.Telefono;
                nutricionistaEncontrado.TarjetaProfesional = Nutricionista.TarjetaProfesional;

                _appContext.SaveChanges();
            }
            return nutricionistaEncontrado;
        }
        public Nutricionista GetNutricionista(int IdNutricionista)
        {
            return _appContext.Nutricionistas.FirstOrDefault(n => n.Id == IdNutricionista);
        }
        public void DeleteNutricionista(int IdNutricionista)
        {
            var nutricionistaEncontrado = _appContext.Nutricionistas.FirstOrDefault(n => n.Id == IdNutricionista);
            if (nutricionistaEncontrado == null)
                return;
            _appContext.Nutricionistas.Remove(nutricionistaEncontrado);
            _appContext.SaveChanges();
        }
    }
}

**Comment by Sergioabc94** [comment]
**RepositorioNutricionista**

`using System;
using System.Collections.Generic;
using System.Linq;
using NutricionApp.Dominio;

namespace NutricionApp.Persistencia
{
    public class RepositorioNutricionista : IRepositorioNutricionista
    {
        private readonly AppContext _appContext;
        public RepositorioNutricionista(AppContext appContext)
        {
            _appContext = appContext;
        }
        public IEnumerable<Nutricionista> AllNutricionistas()
        {
            return _appContext.Nutricionistas;
        }
        public Nutricionista AddNutricionista(Nutricionista nutricionista)
        {
            var nutricionistaAdicionado = _appContext.Nutricionistas.Add(nutricionista);
            _appContext.SaveChanges();
            return nutricionistaAdicionado.Entity;
        }
        public Nutricionista UpdateNutricionista(Nutricionista Nutricionista)
        {
            var nutricionistaEncontrado = _appContext.Nutricionistas.FirstOrDefault(n => n.Id == Nutricionista.Id);
            if (nutricionistaEncontrado != null)
            {
                nutricionistaEncontrado.Id = Nutricionista.Id;
                nutricionistaEncontrado.Nombre = Nutricionista.Nombre;
                nutricionistaEncontrado.Apellidos = Nutricionista.Apellidos;
                nutricionistaEncontrado.Identificacion = Nutricionista.Identificacion;
                nutricionistaEncontrado.Correo = Nutricionista.Correo;
                nutricionistaEncontrado.Contrasena = Nutricionista.Contrasena;
                nutricionistaEncontrado.Telefono = Nutricionista.Telefono;
                nutricionistaEncontrado.TarjetaProfesional = Nutricionista.TarjetaProfesional;

                _appContext.SaveChanges();
            }
            return nutricionistaEncontrado;
        }
        public Nutricionista GetNutricionista(int IdNutricionista)
        {
            return _appContext.Nutricionistas.FirstOrDefault(n => n.Id == IdNutricionista);
        }
        public void DeleteNutricionista(int IdNutricionista)
        {
            var nutricionistaEncontrado = _appContext.Nutricionistas.FirstOrDefault(n => n.Id == IdNutricionista);
            if (nutricionistaEncontrado == null)
                return;
            _appContext.Nutricionistas.Remove(nutricionistaEncontrado);
            _appContext.SaveChanges();
        }
    }
}
`

**Comment by Sergioabc94** [comment]
## IRepositorioNutricionista

      using System;
      using System.Collections.Generic;
      using NutricionApp.Dominio;
      
      namespace NutricionApp.Persistencia
      {
          public interface IRepositorioNutricionista
          {
              IEnumerable<Nutricionista> AllNutricionistas();
              Nutricionista AddNutricionista(Nutricionista nutricionista);
              Nutricionista UpdateNutricionista(Nutricionista nutricionista);
              Nutricionista GetNutricionista(int IdNutricionista);
              void DeleteNutricionista(int IdNutricionista);
      
          }
      }


## RepositorioNutricionista

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using NutricionApp.Dominio;
    
    namespace NutricionApp.Persistencia
    {
        public class RepositorioNutricionista : IRepositorioNutricionista
        {
            private readonly AppContext _appContext;
            public RepositorioNutricionista(AppContext appContext)
            {
                _appContext = appContext;
            }
            public IEnumerable<Nutricionista> AllNutricionistas()
            {
                return _appContext.Nutricionistas;
            }
            public Nutricionista AddNutricionista(Nutricionista nutricionista)
            {
                var nutricionistaAdicionado = _appContext.Nutricionistas.Add(nutricionista);
                _appContext.SaveChanges();
                return nutricionistaAdicionado.Entity;
            }
            public Nutricionista UpdateNutricionista(Nutricionista Nutricionista)
            {
                var nutricionistaEncontrado = _appContext.Nutricionistas.FirstOrDefault(n => n.Id == Nutricionista.Id);
                if (nutricionistaEncontrado != null)
                {
                    nutricionistaEncontrado.Id = Nutricionista.Id;
                    nutricionistaEncontrado.Nombre = Nutricionista.Nombre;
                    nutricionistaEncontrado.Apellidos = Nutricionista.Apellidos;
                    nutricionistaEncontrado.Identificacion = Nutricionista.Identificacion;
                    nutricionistaEncontrado.Correo = Nutricionista.Correo;
                    nutricionistaEncontrado.Contrasena = Nutricionista.Contrasena;
                    nutricionistaEncontrado.Telefono = Nutricionista.Telefono;
                    nutricionistaEncontrado.TarjetaProfesional = Nutricionista.TarjetaProfesional;
    
                    _appContext.SaveChanges();
                }
                return nutricionistaEncontrado;
            }
            public Nutricionista GetNutricionista(int IdNutricionista)
            {
                return _appContext.Nutricionistas.FirstOrDefault(n => n.Id == IdNutricionista);
            }
            public void DeleteNutricionista(int IdNutricionista)
            {
                var nutricionistaEncontrado = _appContext.Nutricionistas.FirstOrDefault(n => n.Id == IdNutricionista);
                if (nutricionistaEncontrado == null)
                    return;
                _appContext.Nutricionistas.Remove(nutricionistaEncontrado);
                _appContext.SaveChanges();
            }
        }
    }
